name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -buildmode=plugin -o dist/plugin.so src/plugin.go

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: New Binary
